-- DDL for Table RECIPE
CREATE TABLE RECIPE (
    ID_RECIPE BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    COOKING_TIME INT NOT NULL,
    MEAL_TYPE VARCHAR(20) NOT NULL CHECK (MEAL_TYPE IN ('BREAKFAST', 'LUNCH', 'DINNER')),
    PRIMARY KEY (ID_RECIPE)
);

-- DDL for Table INGREDIENT
CREATE TABLE INGREDIENT (
    ID_INGREDIENT BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    ID_RECIPE BIGINT NOT NULL,
    AMOUNT VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_INGREDIENT),
    CONSTRAINT FK_INGREDIENT_RECIPE FOREIGN KEY (ID_RECIPE) REFERENCES RECIPE(ID_RECIPE)
);

-- Unique Indexes
CREATE UNIQUE INDEX UK1_INGREDIENT ON INGREDIENT (NAME, ID_RECIPE, AMOUNT);
-- Unique Indexes
CREATE UNIQUE INDEX UK1_RECIPE ON RECIPE (NAME);