spring:
  application:
    name: recipe-springapp-1

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
  
  liquibase:
    changelog: db/changelog/db.changelog-master.xml  
    enabled: true  

server:
  servlet:
    context-path: /recipes-app/api
  port: 8080
